"""
schema_migration.py

Run this script once to provision the Milvus collection.

Responsibilities:
- Create the collection schema.
- Create vector and metadata indexes.
- Optionally recreate the collection during development.
- Keep schema aligned with the embedding model dimension.


RUN: python -m Others.schema_migration --drop-existing
"""

from pymilvus import MilvusClient, DataType
import argparse
import sys

from config import MILVUS_URI, collection_name
from services.AI_models import get_embedding_model


def provision(drop_existing: bool = False):
    """
    Creates the collection if it does not exist.

    Args:
        drop_existing:
            False -> keep existing collection.
            True  -> delete and recreate collection.
    """

    # Connect to the Milvus server.
    client = MilvusClient(uri=MILVUS_URI)

    # ------------------------------------------------------------------
    # Check whether the collection already exists.
    # ------------------------------------------------------------------
    if client.has_collection(collection_name):

        if not drop_existing:
            print(f"Collection '{collection_name}' already exists.")
            return

        # WARNING:
        # This permanently deletes the collection and all stored data.
        # Useful during development when the schema changes.
        client.drop_collection(collection_name)

        print(
            f"Dropped existing collection : {collection_name}."
        )

    # ------------------------------------------------------------------
    # Determine embedding dimension dynamically.
    #
    # Avoids hardcoding dimensions such as:
    # - 1536 (OpenAI text-embedding-3-small)
    # - 3072 (OpenAI text-embedding-3-large)
    # - 1024 (BGE models)
    #
    # The vector field dimension MUST match the selected embedding model.
    # ------------------------------------------------------------------
    dim = len(get_embedding_model().embed_query("testing dimension probe"))

    # ------------------------------------------------------------------
    # Create schema.
    #
    # auto_id=True:
    #   Milvus generates primary keys automatically.
    #
    # enable_dynamic_field=True:
    #   Allows storing additional metadata fields in the future
    #   without modifying the schema.
    # ------------------------------------------------------------------
    schema = client.create_schema(
        auto_id=True,
        enable_dynamic_field=True
    )

    # ------------------------------------------------------------------
    # Primary key
    #
    # Auto-generated by Milvus.
    # No need to manually create unique IDs during ingestion.
    # ------------------------------------------------------------------
    schema.add_field(
        field_name="pk",
        datatype=DataType.INT64,
        is_primary=True,
        auto_id=True
    )

    # ------------------------------------------------------------------
    # Main searchable text.
    #
    # This is the content that gets retrieved and sent to the LLM
    # after similarity search.
    # ------------------------------------------------------------------
    schema.add_field(
        field_name="text",
        datatype=DataType.VARCHAR,
        max_length=65535
    )

    # ------------------------------------------------------------------
    # Embedding vector used for semantic search.
    #
    # Dimension must exactly match the embedding model output.
    # ------------------------------------------------------------------
    schema.add_field(
        field_name="vector",
        datatype=DataType.FLOAT_VECTOR,
        dim=dim
    )

    # ==================================================================
    # Product Metadata Fields
    # ==================================================================

    # Human-readable product title.
    schema.add_field(
        field_name="product_name",
        datatype=DataType.VARCHAR,
        max_length=512,
        nullable=True
    )

    # Brand name.
    # Enables filters such as:
    # brand == "Apple"
    schema.add_field(
        field_name="brand",
        datatype=DataType.VARCHAR,
        max_length=128,
        nullable=True
    )

    # Product grouping/category.
    # Example:
    # Electronics, Furniture, Clothing, Books
    schema.add_field(
        field_name="category",
        datatype=DataType.VARCHAR,
        max_length=128,
        nullable=True
    )

    # Product price.
    # Consider FLOAT if exact money precision is required.
    schema.add_field(
        field_name="price",
        datatype=DataType.FLOAT,
        nullable=True
    )

    # Customer rating.
    # Useful for ranking and filtering.
    schema.add_field(
        field_name="rating",
        datatype=DataType.FLOAT,
        nullable=True
    )

    # Current inventory count.
    # Allows filters such as:
    # stock > 0
    schema.add_field(
        field_name="stock",
        datatype=DataType.INT64,
        nullable=True
    )

    # Structured product attributes.
    #
    # Example:
    # "Bluetooth 5.3, Waterproof, Fast Charging"
    schema.add_field(
        field_name="features",
        datatype=DataType.VARCHAR,
        max_length=2048,
        nullable=True
    )

    # Detailed product description.
    # Can be stored separately from the searchable text chunk.
    schema.add_field(
        field_name="description",
        datatype=DataType.VARCHAR,
        max_length=4096,
        nullable=True
    )

    # ------------------------------------------------------------------
    # Prepare indexes.
    #
    # Indexes significantly improve search and filter performance.
    # ------------------------------------------------------------------
    index_params = client.prepare_index_params()

    # ------------------------------------------------------------------
    # Vector Index (HNSW)
    #
    # HNSW:
    #   Fast and accurate approximate nearest-neighbor search.
    #
    # COSINE:
    #   Recommended for most modern embedding models.
    #
    # M:
    #   Number of graph connections per node.
    #
    # efConstruction:
    #   Controls index build quality.
    #   Higher = better recall but slower index creation.
    # ------------------------------------------------------------------
    index_params.add_index(
        field_name="vector",
        index_type="HNSW",
        metric_type="COSINE",
        params={
            "M": 16,  # typically between 16-32
            "efConstruction": 200  # typically between 100-500
        }
    )

    # ------------------------------------------------------------------
    # Metadata indexes.
    #
    # Accelerates filters such as:
    #
    # brand == "Samsung"
    # category == "Mobile"
    # rating >= 4.5
    # stock > 0
    # ------------------------------------------------------------------
    for field in (
            "product_name",
            "brand",
            "category",
            "price",
            "rating",
            "stock"
    ):
        index_params.add_index(
            field_name=field,
            index_type="INVERTED"
        )

    # ------------------------------------------------------------------
    # Create collection with schema and indexes.
    #
    # Strong consistency ensures newly written data is immediately
    # visible to subsequent reads.
    # ------------------------------------------------------------------
    client.create_collection(
        collection_name=collection_name,
        schema=schema,
        index_params=index_params,
        consistency_level="Strong"
    )

    # ------------------------------------------------------------------
    # Optional:
    #
    # Load collection into memory immediately.
    #
    # Useful if searches begin immediately after provisioning.
    # Many applications load collections automatically later.
    # ------------------------------------------------------------------
    # client.load_collection(collection_name)

    print(
        f"Created collection '{collection_name}' "
        f"with embedding dimension {dim}"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Provision Milvus collection"
    )

    parser.add_argument(
        "--drop-existing",
        action="store_true",
        help="Drop and recreate the collection (DANGEROUS)"
    )

    args = parser.parse_args()

    # ---------------------------------------------------------
    # Safety guard for destructive operation
    # ---------------------------------------------------------
    if args.drop_existing:
        confirm = input(
            "⚠ This will DELETE all collection data. Type 'yes' to continue: "
        ).strip().lower()

        if confirm != "yes":
            print("Operation cancelled.")
            sys.exit(0)

    provision(drop_existing=args.drop_existing)
